services:
  blog:
    image: blog
    build: .
    depends_on:
      - pg
    ports: 
      - "8080:8080"
    environment:
      DB_URL: $DB_URL
      DB_USERNAME: $DB_USERNAME
      DB_PASSWORD: $DB_PASSWORD
      IMAGES_DIR: $IMAGES_DIR
  pg:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: postgres
    ports: 
      - "5432:5432"